name: Build and Publish
on:
  push:
    branches:
      - 1.9.0-rc.1
      - master
      - beta
      - stable
      - post-phase-1
jobs:
  build_binary:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2020-03-19
    - uses: actions/checkout@master
    - uses: chrislennon/action-aws-cli@v1.1
    - run: scripts/binary-release.sh
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEPLOY_VERSION: ${{ secrets.DEPLOY_VERSION }}  
